apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "8.10.0"
  values:
    adminUser: admin
    adminPassword: admin123
    service:
      type: NodePort
      nodePort: 30000
