apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "6.42.0"
  values:
    deploymentMode: SingleBinary
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    singleBinary:
      replicas: 1
      persistence:
        enabled: false
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "250m"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      chunksCache:
        enabled: false
      resultsCache:
        enabled: false
    podSecurityPolicy:
      enabled: false
    rbac:
      create: true
    loki:
      auth_enabled: false
      useTestSchema: true
      storage:
        type: filesystem
      config: |
        server:
          http_listen_port: 3100
        common:
          path_prefix: /var/loki
          replication_factor: 1
          storage:
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
        ruler:
          storage:
            type: local
            local:
              directory: /var/loki/rules
        table_manager:
          retention_deletes_enabled: true
          retention_period: 1d
