apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "6.42.0"
  values:
    podSecurityPolicy:
      enabled: false
    rbac:
      create: true
    persistence:
      enabled: true
      size: 1Gi
    loki:
      auth_enabled: false
      storage:
        type: filesystem
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 1d
