apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "6.42.0"
  values:
    deploymentMode: SingleBinary
    podSecurityPolicy:
      enabled: false
    rbac:
      create: true
    persistence:
      enabled: true
      size: 1Gi
    loki:
      auth_enabled: false
      storage:
        type: filesystem
      config: |
        server:
          http_listen_port: 3100
        common:
          path_prefix: /var/loki
          storage:
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          replication_factor: 1
        ruler:
          storage:
            type: local
            local:
              directory: /var/loki/rules
        table_manager:
          retention_deletes_enabled: true
          retention_period: 1d
