name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - release
      - master

env:
  APP_NAME: hello-world
  DOCKER_REGISTRY: rahsnh

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout application code
      - name: Checkout app code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: Determine environment based on branch
      - name: Set environment
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "release" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          else
            echo "Unknown branch"
            exit 1
          fi
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE=$DOCKER_REGISTRY/${APP_NAME}:${IMAGE_TAG}
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Step 5: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE

      # Step 7: Checkout k8s-apps repo
      - name: Checkout k8s-apps repo
        uses: actions/checkout@v3
        with:
          repository: rahsnh/k8s-apps
          token: ${{ secrets.GITHUB_TOKEN }}
          path: k8s-apps
          ref: main

      # Step 8: Update Helm values file for environment
      - name: Update Helm values file with sed
        run: |
          VALUES_FILE=k8s-apps/values-${ENV}/${APP_NAME}.yaml
          sed -i "s|tag: .*|tag: ${IMAGE_TAG}|g" $VALUES_FILE

      # Step 9: Commit & push changes to k8s-apps
      - name: Commit & push updated values
        run: |
          cd k8s-apps
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update ${APP_NAME} image to ${IMAGE_TAG} for ${ENV}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
