name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: Build Docker image
      - name: Build Docker image
        id: set-image
        run: |
          IMAGE=rahsnh/hello-world:${GITHUB_SHA::7}
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "::set-output name=image::$IMAGE"

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push Docker image
      - name: Push Docker image
        run: docker push $IMAGE

      # Step 6: Update deployment.yaml with new image
      - name: Update deployment.yaml with new image
        run: |
          sed -i "s|image: .*|image: $IMAGE|g" manifests/deployment.yaml

      # Step 7: Commit & push updated deployment.yaml
      - name: Commit & push updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image to $IMAGE" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
