name: Deploy to Kubernetes via ArgoCD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (staging/production)'
        required: true
        default: 'staging'
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the selected branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # Step 2: Install ArgoCD CLI
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd version

      # Step 3: ArgoCD Sync
      - name: ArgoCD Sync
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          # Fail early if secrets are missing
          if [ -z "$ARGOCD_SERVER" ] || [ -z "$ARGOCD_AUTH_TOKEN" ]; then
            echo "ERROR: ARGOCD_SERVER or ARGOCD_AUTH_TOKEN not set"
            exit 1
          fi

          echo "Deploying branch '${{ github.event.inputs.branch }}' to environment '${{ github.event.inputs.environment }}'"

          # Trigger ArgoCD app sync
          argocd app sync hello-world \
            --server $ARGOCD_SERVER \
            --auth-token $ARGOCD_AUTH_TOKEN \
            --prune \
            --wait \
            --insecure
